TARGET = mem_manager
DEPS = memory process_sim
CC = gcc
FLAGS = -O3 -std=c11

.PHONY: clean

all: 
#	$(CC) $(FLAGS) $(DEPS).c -o $(DEPS)
	$(CC) $(FLAGS) $(TARGET).c -o $(TARGET)
clean:
	rm -rf $(TARGET).o $(TARGET)